import React from 'react';
import { BarChart3, Download, FileText, Printer, Shield } from 'lucide-react';
import { printPage, exportToCSV } from '../../utils/calculations';

export const ReportsModule: React.FC = () => {
  const handleDownloadSummary = () => {
    const headers = ['Report Name', 'Period', 'Generated By', 'Status'];
    const rows = [
      ['Monthly Glass Melt Tonnage Report', 'August 2026', 'Ahmed S.', 'Approved'],
      ['OEE & Line Downtime Analysis', 'August 2026', 'Ahmed S.', 'Approved'],
      ['Cold End Quality Defect Pareto', 'August 2026', 'Anita Sharma', 'Approved'],
      ['Energy & Cullet Recycling Audit', 'August 2026', 'Vikram Singh', 'Approved'],
    ];
    exportToCSV('Vitrum_Glass_Executive_Reports_August_2026', headers, rows);
  };

  return (
    <div className="p-4 md:p-6 space-y-6 max-w-[1920px] mx-auto animate-in fade-in duration-200">
      <div className="flex flex-wrap items-center justify-between gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-2xs">
        <div>
          <h1 className="text-xl font-bold text-slate-900">Vitrum Glass Executive & Technical Reports</h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Furnace Energy Consumption, Machine OEE, Quality Defect Pareto & Dispatch Velocity
          </p>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={printPage}
            className="px-3 py-1.5 border border-slate-300 rounded-lg text-xs font-semibold text-slate-700 bg-white hover:bg-slate-50 flex items-center gap-1.5"
          >
            <Printer className="w-3.5 h-3.5" /> Print All
          </button>
          <button
            onClick={handleDownloadSummary}
            className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold flex items-center gap-1.5"
          >
            <Download className="w-3.5 h-3.5" /> Download Report Pack
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-2xs space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-blue-100 text-blue-700 rounded-lg flex items-center justify-center font-bold">
              <BarChart3 className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">Monthly Glass Melt Tonnage Report</h3>
              <p className="text-xs text-slate-500">Furnace Tonnage Budget vs Actual Melt Draw</p>
            </div>
          </div>
          <p className="text-xs text-slate-600 leading-relaxed">
            Consolidated daily tonnage draw across 6 IS Forming lines. Average daily furnace melt: 442.5 Tons/day (98.3% target compliance).
          </p>
          <button
            onClick={handleDownloadSummary}
            className="text-xs text-blue-600 font-bold hover:underline flex items-center gap-1"
          >
            Export Excel CSV →
          </button>
        </div>

        <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-2xs space-y-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-emerald-100 text-emerald-700 rounded-lg flex items-center justify-center font-bold">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-slate-900">OEE & Line Downtime Analysis</h3>
              <p className="text-xs text-slate-500">IS Machine Efficiency, Mold Swap & Shears Breakdown</p>
            </div>
          </div>
          <p className="text-xs text-slate-600 leading-relaxed">
            Total planned downtime: 31.0 hours (Mold changeovers: 14.5 hrs, Feeder temp adjustments: 6.2 hrs).
          </p>
          <button
            onClick={handleDownloadSummary}
            className="text-xs text-blue-600 font-bold hover:underline flex items-center gap-1"
          >
            Export Excel CSV →
          </button>
        </div>
      </div>
    </div>
  );
};
